# configuration for mapping functions
maps:
  base:
    fill: "grey90"
    color: "gray50"

# palette definition
palettes:
  cat:
    [
      ["#1188A6"],
      ["#1188A6","#E54E4D"],
      ["#1188A6","#E54E4D","#142052"],
      ["#1188A6","#E54E4D","#142052","#8D2120"],
      ["#1188A6","#E54E4D","#142052","#8D2120","#12547C"],
      ["#1188A6","#E54E4D","#142052","#8D2120","#12547C","#5393EA"],
      ["#1188A6","#E54E4D","#142052","#8D2120","#12547C","#5393EA","#2FB064"],
      ["#1188A6","#E54E4D","#142052","#8D2120","#12547C","#5393EA","#2FB064","#956923"],
      ["#1188A6","#E54E4D","#142052","#8D2120","#12547C","#5393EA","#2FB064","#956923","#DC479F"]
    ]
  seq:
    [
      ["#1188A6"],
      ["#1188A6","#117B9B"],
      ["#1188A6","#117B9B","#116E91"],
      ["#1188A6","#117B9B","#116E91","#126186"],
      ["#1188A6","#117B9B","#116E91","#126186","#12547C"],
      ["#1188A6","#117B9B","#116E91","#126186","#12547C","#134771"],
      ["#1188A6","#117B9B","#116E91","#126186","#12547C","#134771","#133A67"],
      ["#1188A6","#117B9B","#116E91","#126186","#12547C","#134771","#133A67","#142D5C"],
      ["#1188A6","#117B9B","#116E91","#126186","#12547C","#134771","#133A67","#142D5C","#142052"]
    ]
  div:
    [
      ["#fff7fb"],
      ["#fff7fb","#ece7f2"],
      ["#fff7fb","#ece7f2","#d0d1e6"],
      ["#fff7fb","#ece7f2","#d0d1e6","#a6bddb"],
      ["#fff7fb","#ece7f2","#d0d1e6","#a6bddb","#74a9cf"],
      ["#fff7fb","#ece7f2","#d0d1e6","#a6bddb","#74a9cf","#3690c0"],
      ["#fff7fb","#ece7f2","#d0d1e6","#a6bddb","#74a9cf","#3690c0","#0570b0"],
      ["#fff7fb","#ece7f2","#d0d1e6","#a6bddb","#74a9cf","#3690c0","#0570b0","#045a8d"],
      ["#fff7fb","#ece7f2","#d0d1e6","#a6bddb","#74a9cf","#3690c0","#0570b0","#045a8d","#023858"]
    ]
  tpl_main:
    oxfordblue: "#151248"
    carminepink: "#E54E4D"
    lightblue: "#5393EA"
    tomato: "#FF6542"
    pineapple: "#564154"
    uclablue: "#556F91"
    pink: "#DC479F"
    desertsand: "#EAD2AC"
    turquoise: "#41EAD4"
  tpl_diverging:
    #red1: "#67001f"
    red2:  "#b2182b"
    red3:  "#d6604d"
    red4:  "#f4a582"
    red5:  "#fddbc7"
    neutr: "#f7f7f7"
    blue5: "#d1e5f0"
    blue4: "#92c5de"
    blue3: "#4393c3"
    blue2: "#2166ac"
    #blue1: "#053061"
  tpl_sequential:
    blue1: "#f7fbff"
    blue2: "#deebf7"
    blue3: "#c6dbef"
    blue4: "#9ecae1"
    blue5: "#6baed6"
    blue6: "#4292c6"
    blue7: "#2171b5"
    blue8: "#08519c"
    blue9: "#08306b"
